import Head from "next/head";
import { Inter } from "next/font/google";
import { CustomTimeline } from "@src/components/CustomTimeline";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>DashFuel Test - Bruno Motta</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={`${inter.className}`}>
				<CustomTimeline />
			</main>
		</>
	);
}
